### ISSUE TITLE
Now you can load the url of the domain.

### ISSUE THREAD

**Issue by bunlongheng** [roke22/Laravel-ssh-client#26]
What do you mean by that ? 

I tried to load my IP, I see 

403 Forbidden
nginx/1.18.0 (Ubuntu)

Please have a look
http://172.105.157.61/

I followed everything on your steps and set my document like this 

root /home/bheng/Laravel-ssh-client/ssh-server;

**Comment by roke22** [comment]
Seems that you have to configure your webserver. If you have nginx look the laravel instructions about how configure nginx https://laravel.com/docs/8.x/deployment#nginx
