### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by perfectwebtech** [roke22/Laravel-ssh-client#4]
hello

in same browser possible connect second tab  third tab like if we have 4 or 5 server then sepeat tab wise connection ?

**Comment by roke22** [comment]
Yes you should be allowed to do it.

**Comment by perfectwebtech** [comment]
how can do it ? any hint or something case terminal id replacing old tab as new tabl replacing old tab always terminal class or id i think replacing all time old connected server to new credential and new server

**Comment by roke22** [comment]
Let me look this and i will reply you in a day or two. Don't remember how
it works so i have to take a look at it.

Jose J. Anton
