### ISSUE TITLE
I can run web socket 

### ISSUE THREAD

**Issue by jjuandiaz** [roke22/Laravel-ssh-client#9]
I downloaded proyect but get connection refused 
how I can know what happened?

WebSocket connection to 'ws://localhost:8090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
connectServer @ 1:33

I run command 
php ssh-server/bin/websocket.php 2>&1 >/dev/null &
[1] 5980
![image](https://user-images.githubusercontent.com/59715844/104214193-e6e8e080-5415-11eb-975b-2db621833ed0.png)

**Comment by roke22** [comment]
Hello!!!

You must change the localhost for the url of the server you are running the
websocket.

In spanish:
Debes modificar localhost por la url del servidor donde tienes corriendo el
websocket.

Jose J. Anton
